# Generated by Django 2.2.24 on 2023-10-14 15:04

from django.db import migrations


def autofill_field_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lte=2015).update(new_building=False)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(autofill_field_new_building)
    ]
