# Generated by Django 2.2.24 on 2023-10-19 15:41

from django.db import migrations
import phonenumbers


def copy_owners_phonenumber_to_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.iterator()
    for flat in flats:
        pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(pure_phone):
            flat.owner_pure_phone = phonenumbers.format_number(pure_phone, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20231017_1012'),
    ]

    operations = [
        migrations.RunPython(copy_owners_phonenumber_to_owner_pure_phone),
    ]
