# Generated by Django 2.2.24 on 2023-10-25 20:40

from django.db import migrations, models


def copy_owners_to_model_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    owners = Owner.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber,
        )
    for owner in owners:
        flats_to_link = Flat.objects.filter(
            owner=owner.owner,
            owners_phonenumber=owner.owners_phonenumber
        )
        owner.flat.set(flats_to_link)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owners_to_model_owner),
    ]
